### ISSUE TITLE
关于easycom配置

### ISSUE THREAD

**Issue by tz95827** [SoulLyoko/uvue-crud#1]
"^uvue(.*)": "uvue-crud/components/uvue-$1/uvue-$1.vue",
是不是要加个“-”变成：
"^uvue-(.*)": "uvue-crud/components/uvue-$1/uvue-$1.vue",

**Comment by SoulLyoko** [comment]
> "^uvue(._)": "uvue-crud/components/uvue-$1/uvue-$1.vue", 是不是要加个“-”变成： "^uvue-(._)": "uvue-crud/components/uvue-$1/uvue-$1.vue",

是的，感谢指正
